spring.application.name=hackerrank
spring.datasource.url=jdbc:postgresql://localhost:5432/user
spring.jpa.show-sql=true
spring.datasource.username=postgres
spring.datasource.password=postgres1
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.mvc.view.prefix=classpath:/templates/
spring.mvc.view.suffix=.html
spring.profiles.active=dev
spring.main.web-application-type=servlet